export const EDIT_CELL = 'EDIT_CELL';
export const EDIT_CELL_EXPENSE = 'EDIT_CELL_EXPENSE'
export const EDIT_CELL_SAVINGS = 'EDIT_CELL_SAVINGS'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const SET_TRANSACTION = 'SET_TRANSACTION'